apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploymentconfig.yaml

openapi:
  path: schemas/deploymentconfig.json

patches:
  - patch: |
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      metadata:
        name: portal
      spec:
        template:
          spec:
            containers:
            - name: portal
              resources:
                limits:
                  cpu: "1"
                  memory: 512Mi
                requests:
                  cpu: "0.5"
                  memory: 256Mi
